### ISSUE TITLE
The InfoBox overshadows the menu

### ISSUE THREAD

**Issue by 1ndexZero** [Kanaru92/DokuWiki-InfoBox#8]
I used Minimal as a template and its menu was overridden by the InfoBox.

<img width="1260" height="893" alt="Image" src="https://github.com/user-attachments/assets/c1c4ceb6-2c18-4255-80df-45d00f2b2cfe" />

**Comment by kanaru-dev** [comment]
This should be resolved now, thanks!

**Comment by 1ndexZero** [comment]
> 现在应该解决了，谢谢！

I have installed v2.2 but it is still the same as before😭
The template I used was Minimal

**Comment by 1ndexZero** [comment]
> This should be resolved now, thanks!

I have installed v2.2 but it is still the same as before😭
The template I used was Minimal
I think it might be a problem with the template

**Comment by 1ndexZero** [comment]
It has been fixed in the Minimal, it added a higher z-index :>

https://github.com/ReactiveMatter/dokuwiki-template-minimal/issues/10
